/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> } 
 */
export const seed = async (knex) => {
  await knex('permission').del()
  await knex('permission').insert([
    // superadmin 
    {
      id: 1, 
      ability_id: 1,
      entity_id: 1,
      entity_type: "role",
    },
    {
      id: 2, 
      ability_id: 2,
      entity_id: 1,
      entity_type: "role",
    },
    {
      id: 3, 
      ability_id: 3,
      entity_id: 1,
      entity_type: "role",
    },
    {
      id: 4, 
      ability_id: 4,
      entity_id: 1,
      entity_type: "role",
    },
    {
      id: 5, 
      ability_id: 5,
      entity_id: 1,
      entity_type: "role",
    },
    {
      id: 6, 
      ability_id: 6,
      entity_id: 1,
      entity_type: "role",
    },
    {
      id: 7, 
      ability_id: 7,
      entity_id: 1,
      entity_type: "role",
    },
    {
      id: 8, 
      ability_id: 8,
      entity_id: 1,
      entity_type: "role",
    },
    {
      id: 9, 
      ability_id: 9,
      entity_id: 1,
      entity_type: "role",
    },
    {
      id: 10, 
      ability_id: 10,
      entity_id: 1,
      entity_type: "role",
    },
    {
      id: 11, 
      ability_id: 11,
      entity_id: 1,
      entity_type: "role",
    },
    {
      id: 12, 
      ability_id: 12,
      entity_id: 1,
      entity_type: "role",
    },
    {
      id: 13, 
      ability_id: 13,
      entity_id: 1,
      entity_type: "role",
    },
    {
      id: 14, 
      ability_id: 14,
      entity_id: 1,
      entity_type: "role",
    },
    {
      id: 15, 
      ability_id: 15,
      entity_id: 1,
      entity_type: "role",
    },
    {
      id: 16, 
      ability_id: 16,
      entity_id: 1,
      entity_type: "role",
    },
    {
      id: 17, 
      ability_id: 17,
      entity_id: 1,
      entity_type: "role",
    },
    {
      id: 18, 
      ability_id: 18,
      entity_id: 1,
      entity_type: "role",
    },
    {
      id: 19, 
      ability_id: 19,
      entity_id: 1,
      entity_type: "role",
    },
    {
      id: 20, 
      ability_id: 20,
      entity_id: 1,
      entity_type: "role",
    },
    {
      id: 21, 
      ability_id: 22,
      entity_id: 1,
      entity_type: "role",
    },
    {
      id: 23, 
      ability_id: 23,
      entity_id: 1,
      entity_type: "role",
    },
    {
      id: 24, 
      ability_id: 24,
      entity_id: 1,
      entity_type: "role",
    },
    {
      id: 25, 
      ability_id: 25,
      entity_id: 1,
      entity_type: "role",
    },
    {
      id: 26, 
      ability_id: 26,
      entity_id: 1,
      entity_type: "role",
    },
    {
      id: 27, 
      ability_id: 27,
      entity_id: 1,
      entity_type: "role",
    },
    {
      id: 28, 
      ability_id: 28,
      entity_id: 1,
      entity_type: "role",
    },
    {
      id: 29, 
      ability_id: 29,
      entity_id: 1,
      entity_type: "role",
    },
    {
      id: 30, 
      ability_id: 30,
      entity_id: 1,
      entity_type: "role",
    },
    {
      id: 31, 
      ability_id: 31,
      entity_id: 1,
      entity_type: "role",
    },
    {
      id: 32, 
      ability_id: 32,
      entity_id: 1,
      entity_type: "role",
    },
    {
      id: 33, 
      ability_id: 33,
      entity_id: 1,
      entity_type: "role",
    },
    {
      id: 34, 
      ability_id: 34,
      entity_id: 1,
      entity_type: "role",
    },
    {
      id: 35, 
      ability_id: 35,
      entity_id: 1,
      entity_type: "role",
    },
    {
      id: 36, 
      ability_id: 36,
      entity_id: 1,
      entity_type: "role",
    },
    {
      id: 37, 
      ability_id: 37,
      entity_id: 1,
      entity_type: "role",
    },
    {
      id: 38, 
      ability_id: 38,
      entity_id: 1,
      entity_type: "role",
    },
    {
      id: 39, 
      ability_id: 39,
      entity_id: 1,
      entity_type: "role",
    },
    // admin
    {
      id: 40, 
      ability_id: 1,
      entity_id: 2,
      entity_type: "role",
    },
    {
      id: 42, 
      ability_id: 2,
      entity_id: 2,
      entity_type: "role",
    },
    {
      id: 43, 
      ability_id: 3,
      entity_id: 2,
      entity_type: "role",
    },
    {
      id: 44, 
      ability_id: 4,
      entity_id: 2,
      entity_type: "role",
    },
    {
      id: 45, 
      ability_id: 5,
      entity_id: 2,
      entity_type: "role",
    },
    {
      id: 46, 
      ability_id: 6,
      entity_id: 2,
      entity_type: "role",
    },
    {
      id: 47, 
      ability_id: 7,
      entity_id: 2,
      entity_type: "role",
    },
    {
      id: 48, 
      ability_id: 8,
      entity_id: 2,
      entity_type: "role",
    },
    {
      id: 49, 
      ability_id: 9,
      entity_id: 2,
      entity_type: "role",
    },
    {
      id: 50, 
      ability_id: 10,
      entity_id: 2,
      entity_type: "role",
    },
    {
      id: 51, 
      ability_id: 11,
      entity_id: 2,
      entity_type: "role",
    },
    {
      id: 52, 
      ability_id: 12,
      entity_id: 2,
      entity_type: "role",
    },
    {
      id: 53, 
      ability_id: 13,
      entity_id: 2,
      entity_type: "role",
    },
    {
      id: 54, 
      ability_id: 14,
      entity_id: 2,
      entity_type: "role",
    },
    {
      id: 55, 
      ability_id: 15,
      entity_id: 2,
      entity_type: "role",
    },
    {
      id: 56, 
      ability_id: 16,
      entity_id: 2,
      entity_type: "role",
    },
    {
      id: 57, 
      ability_id: 17,
      entity_id: 2,
      entity_type: "role",
    },
    {
      id: 58, 
      ability_id: 18,
      entity_id: 2,
      entity_type: "role",
    },
    {
      id: 59, 
      ability_id: 19,
      entity_id: 2,
      entity_type: "role",
    },
    {
      id: 60, 
      ability_id: 20,
      entity_id: 2,
      entity_type: "role",
    },
    {
      id: 61, 
      ability_id: 22,
      entity_id: 2,
      entity_type: "role",
    },
    {
      id: 63, 
      ability_id: 23,
      entity_id: 2,
      entity_type: "role",
    },
    {
      id: 64, 
      ability_id: 24,
      entity_id: 2,
      entity_type: "role",
    },
    {
      id: 65, 
      ability_id: 25,
      entity_id: 2,
      entity_type: "role",
    },
    {
      id: 66, 
      ability_id: 26,
      entity_id: 2,
      entity_type: "role",
    },
    {
      id: 67, 
      ability_id: 27,
      entity_id: 2,
      entity_type: "role",
    },
    {
      id: 68, 
      ability_id: 28,
      entity_id: 2,
      entity_type: "role",
    },
    {
      id: 69, 
      ability_id: 29,
      entity_id: 2,
      entity_type: "role",
    },
    {
      id: 70, 
      ability_id: 30,
      entity_id: 2,
      entity_type: "role",
    },
    {
      id: 71, 
      ability_id: 31,
      entity_id: 2,
      entity_type: "role",
    },
    {
      id: 72, 
      ability_id: 32,
      entity_id: 2,
      entity_type: "role",
    },
    {
      id: 73, 
      ability_id: 33,
      entity_id: 2,
      entity_type: "role",
    },
    {
      id: 74, 
      ability_id: 34,
      entity_id: 2,
      entity_type: "role",
    },
    {
      id: 75, 
      ability_id: 35,
      entity_id: 2,
      entity_type: "role",
    },
    {
      id: 76, 
      ability_id: 36,
      entity_id: 2,
      entity_type: "role",
    },
    {
      id: 77, 
      ability_id: 37,
      entity_id: 2,
      entity_type: "role",
    },
    {
      id: 78, 
      ability_id: 38,
      entity_id: 2,
      entity_type: "role",
    },
    {
      id: 79, 
      ability_id: 39,
      entity_id: 2,
      entity_type: "role",
    },
    // supervisor
    {
      id: 80, 
      ability_id: 1,
      entity_id: 3,
      entity_type: "role",
    },
    {
      id: 81, 
      ability_id: 2,
      entity_id: 3,
      entity_type: "role",
    },
    {
      id: 82, 
      ability_id: 3,
      entity_id: 3,
      entity_type: "role",
    },
    {
      id: 83, 
      ability_id: 4,
      entity_id: 3,
      entity_type: "role",
    },
    {
      id: 84, 
      ability_id: 7,
      entity_id: 3,
      entity_type: "role",
    },
    {
      id: 85, 
      ability_id: 9,
      entity_id: 3,
      entity_type: "role",
    },
    // webmaster
    {
      id: 86, 
      ability_id: 40,
      entity_id: 4,
      entity_type: "role",
    },
    // operator
    {
      id: 87, 
      ability_id: 1,
      entity_id: 5,
      entity_type: "role",
    },
    {
      id: 88, 
      ability_id: 2,
      entity_id: 5,
      entity_type: "role",
    },
    {
      id: 89, 
      ability_id: 3,
      entity_id: 5,
      entity_type: "role",
    },
    {
      id: 90, 
      ability_id: 4,
      entity_id: 5,
      entity_type: "role",
    },
    // superadmin
    {
      id: 91, 
      ability_id: 41,
      entity_id: 1,
      entity_type: "role",
    },
    {
      id: 92, 
      ability_id: 42,
      entity_id: 1,
      entity_type: "user",
    },
  ]);
};
